version: "3"

services:
  api-server:
    build: ./api-server
    container_name: api-server
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ../:/go/src/app

  prisma-cli:
    build: ./prisma-cli
    container_name: prisma-cli
    tty: true
    volumes:
      - ../:/usr/src/app

  prisma-server:
    image: prismagraphql/prisma:1.34
    container_name: prisma-server
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: database
            port: 3306
            user: root
            password: prisma

  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: ~
